const countries = [
    {
        "name": {
            "common": "Mauritania",
            "official": "Islamic Republic of Mauritania",
            "nativeName": { "ara": { "official": "الجمهورية الإسلامية الموريتانية", "common": "موريتانيا" } }
        },
        "tld": [".mr"],
        "cca2": "MR",
        "ccn3": "478",
        "cca3": "MRT",
        "cioc": "MTN",
        "independent": true,
        "status": "officially-assigned",
        "unMember": true,
        "currencies": { "MRU": { "name": "Mauritanian ouguiya", "symbol": "UM" } },
        "idd": { "root": "+2", "suffixes": ["22"] },
        "capital": ["Nouakchott"],
        "altSpellings": ["MR", "Islamic Republic of Mauritania", "al-Jumhūriyyah al-ʾIslāmiyyah al-Mūrītāniyyah"],
        "region": "Africa",
        "subregion": "Western Africa",
        "languages": { "ara": "Arabic" },
        "translations": {
            "ara": { "official": "الجمهورية الإسلامية الموريتانية", "common": "موريتانيا" },
            "bre": { "official": "Republik islamek Maouritania", "common": "Maouritania" },
            "ces": { "official": "Mauritánská islámská republika", "common": "Mauritánie" },
            "cym": { "official": "Islamic Republic of Mauritania", "common": "Mauritania" },
            "deu": { "official": "Islamische Republik Mauretanien", "common": "Mauretanien" },
            "est": { "official": "Mauritaania Islamivabariik", "common": "Mauritaania" },
            "fin": { "official": "Mauritanian islamilainen tasavalta", "common": "Mauritania" },
            "fra": { "official": "République islamique de Mauritanie", "common": "Mauritanie" },
            "hrv": { "official": "Islamska Republika Mauritanija", "common": "Mauritanija" },
            "hun": { "official": "Mauritániai Iszlám Köztársaság", "common": "Mauritánia" },
            "ita": { "official": "Repubblica islamica di Mauritania", "common": "Mauritania" },
            "jpn": { "official": "モーリタニア·イスラム共和国", "common": "モーリタニア" },
            "kor": { "official": "모리타니 이슬람 공화국", "common": "모리타니" },
            "nld": { "official": "Islamitische Republiek Mauritanië", "common": "Mauritanië" },
            "per": { "official": "جمهوری اسلامی موریتانی", "common": "موریتانی" },
            "pol": { "official": "Islamska Republika Mauretańska", "common": "Mauretania" },
            "por": { "official": "República Islâmica da Mauritânia", "common": "Mauritânia" },
            "rus": { "official": "Исламская Республика Мавритания", "common": "Мавритания" },
            "slk": { "official": "Mauritánska islamská republika", "common": "Mauritánia" },
            "spa": { "official": "República Islámica de Mauritania", "common": "Mauritania" },
            "swe": { "official": "Islamiska republiken Mauretanien", "common": "Mauretanien" },
            "tur": { "official": "Moritanya İslam Cumhuriyeti", "common": "Moritanya" },
            "urd": { "official": "اسلامی جمہوریہ موریتانیہ", "common": "موریتانیہ" },
            "zho": { "official": "毛里塔尼亚伊斯兰共和国", "common": "毛里塔尼亚" }
        },
        "latlng": [20.0, -12.0],
        "landlocked": false,
        "borders": ["DZA", "MLI", "SEN", "ESH"],
        "area": 1030700.0,
        "demonyms": {
            "eng": { "f": "Mauritanian", "m": "Mauritanian" },
            "fra": { "f": "Mauritanienne", "m": "Mauritanien" }
        },
        "flag": "\uD83C\uDDF2\uD83C\uDDF7",
        "maps": {
            "googleMaps": "https://goo.gl/maps/im2MmQ5jFjzxWBks5",
            "openStreetMaps": "https://www.openstreetmap.org/relation/192763"
        },
        "population": 4649660,
        "gini": { "2014": 32.6 },
        "fifa": "MTN",
        "car": { "signs": ["RIM"], "side": "right" },
        "timezones": ["UTC"],
        "continents": ["Africa"],
        "flags": { "png": "https://flagcdn.com/w320/mr.png", "svg": "https://flagcdn.com/mr.svg" },
        "coatOfArms": {
            "png": "https://mainfacts.com/media/images/coats_of_arms/mr.png",
            "svg": "https://mainfacts.com/media/images/coats_of_arms/mr.svg"
        },
        "startOfWeek": "monday",
        "capitalInfo": { "latlng": [18.07, -15.97] }
    },
    {
        "name": {
            "common": "Aruba",
            "official": "Aruba",
            "nativeName": {
                "nld": { "official": "Aruba", "common": "Aruba" },
                "pap": { "official": "Aruba", "common": "Aruba" }
            }
        },
        "tld": [".aw"],
        "cca2": "AW",
        "ccn3": "533",
        "cca3": "ABW",
        "cioc": "ARU",
        "independent": false,
        "status": "officially-assigned",
        "unMember": false,
        "currencies": { "AWG": { "name": "Aruban florin", "symbol": "ƒ" } },
        "idd": { "root": "+2", "suffixes": ["97"] },
        "capital": ["Oranjestad"],
        "altSpellings": ["AW"],
        "region": "Americas",
        "subregion": "Caribbean",
        "languages": { "nld": "Dutch", "pap": "Papiamento" },
        "translations": {
            "ara": { "official": "أروبا", "common": "أروبا" },
            "bre": { "official": "Aruba", "common": "Aruba" },
            "ces": { "official": "Aruba", "common": "Aruba" },
            "cym": { "official": "Aruba", "common": "Aruba" },
            "deu": { "official": "Aruba", "common": "Aruba" },
            "est": { "official": "Aruba", "common": "Aruba" },
            "fin": { "official": "Aruba", "common": "Aruba" },
            "fra": { "official": "Aruba", "common": "Aruba" },
            "hrv": { "official": "Aruba", "common": "Aruba" },
            "hun": { "official": "Aruba", "common": "Aruba" },
            "ita": { "official": "Aruba", "common": "Aruba" },
            "jpn": { "official": "アルバ", "common": "アルバ" },
            "kor": { "official": "아루바", "common": "아루바" },
            "nld": { "official": "Aruba", "common": "Aruba" },
            "per": { "official": "آروبا", "common": "آروبا" },
            "pol": { "official": "Aruba", "common": "Aruba" },
            "por": { "official": "Aruba", "common": "Aruba" },
            "rus": { "official": "Аруба", "common": "Аруба" },
            "slk": { "official": "Aruba", "common": "Aruba" },
            "spa": { "official": "Aruba", "common": "Aruba" },
            "swe": { "official": "Aruba", "common": "Aruba" },
            "tur": { "official": "Aruba", "common": "Aruba" },
            "urd": { "official": "اروبا", "common": "اروبا" },
            "zho": { "official": "阿鲁巴", "common": "阿鲁巴" }
        },
        "latlng": [12.5, -69.96666666],
        "landlocked": false,
        "area": 180.0,
        "demonyms": { "eng": { "f": "Aruban", "m": "Aruban" }, "fra": { "f": "Arubaise", "m": "Arubais" } },
        "flag": "\uD83C\uDDE6\uD83C\uDDFC",
        "maps": {
            "googleMaps": "https://goo.gl/maps/8hopbQqifHAgyZyg8",
            "openStreetMaps": "https://www.openstreetmap.org/relation/1231749"
        },
        "population": 106766,
        "fifa": "ARU",
        "car": { "side": "right" },
        "timezones": ["UTC-04:00"],
        "continents": ["North America"],
        "flags": { "png": "https://flagcdn.com/w320/aw.png", "svg": "https://flagcdn.com/aw.svg" },
        "coatOfArms": {
            "png": "https://mainfacts.com/media/images/coats_of_arms/aw.png",
            "svg": "https://mainfacts.com/media/images/coats_of_arms/aw.svg"
        },
        "startOfWeek": "monday",
        "capitalInfo": { "latlng": [12.52, -70.03] }
    },
    {
        "name": {
            "common": "Argentina",
            "official": "Argentine Republic",
            "nativeName": {
                "grn": { "official": "Argentine Republic", "common": "Argentina" },
                "spa": { "official": "República Argentina", "common": "Argentina" }
            }
        },
        "tld": [".ar"],
        "cca2": "AR",
        "ccn3": "032",
        "cca3": "ARG",
        "cioc": "ARG",
        "independent": true,
        "status": "officially-assigned",
        "unMember": true,
        "currencies": { "ARS": { "name": "Argentine peso", "symbol": "$" } },
        "idd": { "root": "+5", "suffixes": ["4"] },
        "capital": ["Buenos Aires"],
        "altSpellings": ["AR", "Argentine Republic", "República Argentina"],
        "region": "Americas",
        "subregion": "South America",
        "languages": { "grn": "Guaraní", "spa": "Spanish" },
        "translations": {
            "ara": { "official": "جمهورية الأرجنتين", "common": "الأرجنتين" },
            "bre": { "official": "Republik Arc'hantina", "common": "Arc'hantina" },
            "ces": { "official": "Argentinská republika", "common": "Argentina" },
            "cym": { "official": "Gweriniaeth yr Ariannin", "common": "Ariannin" },
            "deu": { "official": "Argentinische Republik", "common": "Argentinien" },
            "est": { "official": "Argentina Vabariik", "common": "Argentina" },
            "fin": { "official": "Argentiinan tasavalta", "common": "Argentiina" },
            "fra": { "official": "République argentine", "common": "Argentine" },
            "hrv": { "official": "Argentinski Republika", "common": "Argentina" },
            "hun": { "official": "Argentin Köztársaság", "common": "Argentína" },
            "ita": { "official": "Repubblica Argentina", "common": "Argentina" },
            "jpn": { "official": "アルゼンチン共和国", "common": "アルゼンチン" },
            "kor": { "official": "아르헨티나 공화국", "common": "아르헨티나" },
            "nld": { "official": "Argentijnse Republiek", "common": "Argentinië" },
            "per": { "official": "جمهوری آرژانتین", "common": "آرژانتین" },
            "pol": { "official": "Republika Argentyńska", "common": "Argentyna" },
            "por": { "official": "República Argentina", "common": "Argentina" },
            "rus": { "official": "Аргентинская Республика", "common": "Аргентина" },
            "slk": { "official": "Argentínska republika", "common": "Argentína" },
            "spa": { "official": "República Argentina", "common": "Argentina" },
            "swe": { "official": "Republiken Argentina", "common": "Argentina" },
            "tur": { "official": "Arjantin Cumhuriyeti", "common": "Arjantin" },
            "urd": { "official": "جمہوریہ ارجنٹائن", "common": "ارجنٹائن" },
            "zho": { "official": "阿根廷共和国", "common": "阿根廷" }
        },
        "latlng": [-34.0, -64.0],
        "landlocked": false,
        "borders": ["BOL", "BRA", "CHL", "PRY", "URY"],
        "area": 2780400.0,
        "demonyms": { "eng": { "f": "Argentine", "m": "Argentine" }, "fra": { "f": "Argentine", "m": "Argentin" } },
        "flag": "\uD83C\uDDE6\uD83C\uDDF7",
        "maps": {
            "googleMaps": "https://goo.gl/maps/Z9DXNxhf2o93kvyc6",
            "openStreetMaps": "https://www.openstreetmap.org/relation/286393"
        },
        "population": 45376763,
        "gini": { "2019": 42.9 },
        "fifa": "ARG",
        "car": { "signs": ["RA"], "side": "right" },
        "timezones": ["UTC-03:00"],
        "continents": ["South America"],
        "flags": { "png": "https://flagcdn.com/w320/ar.png", "svg": "https://flagcdn.com/ar.svg" },
        "coatOfArms": {
            "png": "https://mainfacts.com/media/images/coats_of_arms/ar.png",
            "svg": "https://mainfacts.com/media/images/coats_of_arms/ar.svg"
        },
        "startOfWeek": "monday",
        "capitalInfo": { "latlng": [-34.58, -58.67] },
        "postalCode": { "format": "@####@@@", "regex": "^([A-Z]\\d{4}[A-Z]{3})$" }
    },
    {
        "name": {
            "common": "Sweden",
            "official": "Kingdom of Sweden",
            "nativeName": { "swe": { "official": "Konungariket Sverige", "common": "Sverige" } }
        },
        "tld": [".se"],
        "cca2": "SE",
        "ccn3": "752",
        "cca3": "SWE",
        "cioc": "SWE",
        "independent": true,
        "status": "officially-assigned",
        "unMember": true,
        "currencies": { "SEK": { "name": "Swedish krona", "symbol": "kr" } },
        "idd": { "root": "+4", "suffixes": ["6"] },
        "capital": ["Stockholm"],
        "altSpellings": ["SE", "Kingdom of Sweden", "Konungariket Sverige"],
        "region": "Europe",
        "subregion": "Northern Europe",
        "languages": { "swe": "Swedish" },
        "translations": {
            "ara": { "official": "مملكة السويد", "common": "السويد" },
            "bre": { "official": "Rouantelezh Sveden", "common": "Sveden" },
            "ces": { "official": "Švédské království", "common": "Švédsko" },
            "cym": { "official": "Kingdom of Sweden", "common": "Sweden" },
            "deu": { "official": "Königreich Schweden", "common": "Schweden" },
            "est": { "official": "Rootsi Kuningriik", "common": "Rootsi" },
            "fin": { "official": "Ruotsin kuningaskunta", "common": "Ruotsi" },
            "fra": { "official": "Royaume de Suède", "common": "Suède" },
            "hrv": { "official": "Kraljevina Švedska", "common": "Švedska" },
            "hun": { "official": "Svéd Királyság", "common": "Svédország" },
            "ita": { "official": "Regno di Svezia", "common": "Svezia" },
            "jpn": { "official": "スウェーデン王国", "common": "スウェーデン" },
            "kor": { "official": "스웨덴 왕국", "common": "스웨덴" },
            "nld": { "official": "Koninkrijk Zweden", "common": "Zweden" },
            "per": { "official": "پادشاهی سوئد", "common": "سوئد" },
            "pol": { "official": "Królestwo Szwecji", "common": "Szwecja" },
            "por": { "official": "Reino da Suécia", "common": "Suécia" },
            "rus": { "official": "Королевство Швеция", "common": "Швеция" },
            "slk": { "official": "Švédske kráľovstvo", "common": "Švédsko" },
            "spa": { "official": "Reino de Suecia", "common": "Suecia" },
            "swe": { "official": "Konungariket Sverige", "common": "Sverige" },
            "tur": { "official": "İsveç Krallığı", "common": "İsveç" },
            "urd": { "official": "مملکتِ سویڈن", "common": "سویڈن" },
            "zho": { "official": "瑞典王国", "common": "瑞典" }
        },
        "latlng": [62.0, 15.0],
        "landlocked": false,
        "borders": ["FIN", "NOR"],
        "area": 450295.0,
        "demonyms": { "eng": { "f": "Swedish", "m": "Swedish" }, "fra": { "f": "Suédoise", "m": "Suédois" } },
        "flag": "\uD83C\uDDF8\uD83C\uDDEA",
        "maps": {
            "googleMaps": "https://goo.gl/maps/iqygE491ADVgnBW39",
            "openStreetMaps": "https://www.openstreetmap.org/relation/52822"
        },
        "population": 10353442,
        "gini": { "2018": 30.0 },
        "fifa": "SWE",
        "car": { "signs": ["S"], "side": "right" },
        "timezones": ["UTC+01:00"],
        "continents": ["Europe"],
        "flags": { "png": "https://flagcdn.com/w320/se.png", "svg": "https://flagcdn.com/se.svg" },
        "coatOfArms": {
            "png": "https://mainfacts.com/media/images/coats_of_arms/se.png",
            "svg": "https://mainfacts.com/media/images/coats_of_arms/se.svg"
        },
        "startOfWeek": "monday",
        "capitalInfo": { "latlng": [59.33, 18.05] },
        "postalCode": { "format": "SE-### ##", "regex": "^(?:SE)*(\\d{5})$" }
    }
]
